version: '3'

services:
    mysql-server:
        image: mysql/mysql-server:latest
        environment:
            - MYSQL_ROOT_PASSWORD=Str0ngPass
            - MYSQL_ROOT_HOST=%
        ports:
            - "3306:3306"
